project:
  type: website
  output-dir: docs
  render:
    - index.qmd
    - "D-wave SDK Demonstration Quantum Annealing.ipynb"
    - "D-wave SDK Demonstration Simulated Annealing.ipynb"
    - "Frustrated Magnets via Annealing.ipynb"
    - max-cut-game.qmd

  resources:
    - downloads/
    - assets.txt
    - "D-wave SDK Demonstration Quantum Annealing.ipynb"
    - "D-wave SDK Demonstration Simulated Annealing.ipynb"
    - "Frustrated Magnets via Annealing.ipynb"

website:
  title: "QSTEP"
  favicon: purdue.ico

  navbar:
    right:
      - icon: github
        href: https://github.com/kaufmann-group/qstep-demo
        aria-label: GitHub

  sidebar:
    style: docked
    search: false
    contents:
      - href: index.qmd
        text: Overview
      - section: "Main Tutorials"
        contents:
          - href: max-cut-game.qmd
            text: Max-Cut Game
          - href: "D-wave SDK Demonstration Quantum Annealing.ipynb"
            text: Instructor Demonstration
          - href: "D-wave SDK Demonstration Simulated Annealing.ipynb"
            text: Student Demonstration
      - section: "Additional Topics"
        contents:
          - href: "Frustrated Magnets via Annealing.ipynb"
            text: Frustrated Magnets

format:
  html:
    theme: cosmo
    toc: true
    toc-title: "On this page"
    toc-location: right
    toc-depth: 3
    code-copy: true
    code-overflow: wrap
    smooth-scroll: true
    css: styles.css

execute:
  freeze: auto
